[phases.setup]
nixPkgs = [
  'nodejs_18',
  'chromium',
  'nss',
  'freetype',
  'harfbuzz',
  'ca-certificates',
  'fontconfig',
  'glib',
  'libdrm',
  'libxcb',
  'libxkbcommon',
  'mesa',
  'expat',
  'alsa-lib',
  'atk',
  'cups',
  'dbus',
  'gtk3',
  'pango',
  'nspr',
  'at-spi2-atk',
  'at-spi2-core',
  'libxcomposite',
  'libxdamage',
  'libxext',
  'libxfixes',
  'libxrandr',
  'gbm',
  'libdrm',
  'xorg.libX11',
  'xorg.libxcb'
]

[phases.install]
cmds = ['npm install']

[start]
cmd = 'node server.js'